Electon-Starlabs/Controllers/CategoryController.cs
using Electon_Starlabs.Contracts.Interfaces.Services;
using Electon_Starlabs.Data;
using Electon_Starlabs.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Electon_Starlabs.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IProductService _productservice;
        private readonly ApplicationDbContext _context;
        private readonly IProductImageService _productImageService;

        public CategoryController(IProductService productService, ApplicationDbContext context, IProductImageService imgService)
        {
            _productservice = productService;
            _context = context;
            _productImageService = imgService;
        }
        public async Task<IActionResult> Index(int id)
        {
            List<Product> produktet = await _productservice.FindAll();
            ViewData["Recently"] = produktet.OrderByDescending(produktet => produktet.AddedDate).Take(3).ToList();
            ViewData["MostSale"] = produktet.OrderByDescending(produktet => produktet.Price).Take(3).ToList();
            ViewData["MostViewed"] = produktet.OrderByDescending(produktet => produktet.HitCount).Take(3).ToList();
            ViewBag.ProductImages = await _productImageService.FindAll(id);
            var model = await _productservice.FindByCategory(id);          
            return View(model);
        }
    }
}

Electon-Starlabs/Controllers/OrdersController.cs
using Electon_Starlabs.Contracts.Interfaces.Repositories;
using Electon_Starlabs.Contracts.Interfaces.Services;
using Electon_Starlabs.Data.Cart;
using Electon_Starlabs.Models;
using Electon_Starlabs.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Electon_Starlabs.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IProductService _productService;
        private readonly IProductRepository _productRepository;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        private readonly ICustomerService _customer;
        private readonly UserManager<IdentityUser> _userManager;


        public OrdersController(IProductService productService, IProductRepository productRepository, ShoppingCart shoppingCart, IOrdersService ordersService, ICustomerService customer,UserManager<IdentityUser> userManager)
        {
            _productService = productService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
            _customer = customer;
            _userManager = userManager;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            string userId = _userManager.GetUserId(HttpContext.User);
            Customer costumer = await _customer.FindByIdentityId(userId);
            var orders =  await _ordersService.GetOrdersByUserIdAsync(userId);
            return View(orders);

        }
        [Authorize]
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }
        [Authorize]

        public async Task<IActionResult> Checkout(string firstName, string Lastname, string Address)
        {
            string userId = _userManager.GetUserId(HttpContext.User);
            Customer customer = await _customer.FindByIdentityId(userId);
            var items = _shoppingCart.GetShoppingCartItems();
            ViewBag.Customer = customer;

            return View(items);
        }

        [Authorize]
        public IActionResult GoToPayment()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            return View(items);
        }

        [Authorize]
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            
            var item = await _productService.FindById(id);
            if(item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        [Authorize]
        public async Task<IActionResult> RemoveItemToShoppingCart(int id)
        {
            var item = await _productService.FindById(id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromCard(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        [Authorize]
        public async Task<IActionResult> CompleteOrder(string street)
        {
            string idOfUser = _userManager.GetUserId(HttpContext.User);
            Customer customer = await _customer.FindByIdentityId(idOfUser);
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = idOfUser;
           /* string userEmailAddress = customer.Email;
            string firstName = customer.Name;
            string lastName = customer.Surname;
            string city = customer.City;*/


           await _ordersService.StoreOrderAsync(items,customer);
            await _shoppingCart.ClearShoppingCartAsync();
 
            return View("OrderCompleted");

        }
    }
}

Electon-Starlabs/Controllers/ProductController.cs
using Electon_Starlabs.Contracts.Interfaces.Repositories;
using Electon_Starlabs.Contracts.Interfaces.Services;
using Electon_Starlabs.Data;
using Electon_Starlabs.Models;
using Electon_Starlabs.Services;
using Electon_Starlabs.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Electon_Starlabs.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productservice;
        private readonly IReviewService _reviewService;
        private readonly IReviewRepository _reviewRepository;
        private readonly ApplicationDbContext _context;
        private readonly IProductImageService _productImageService;
        private readonly ICustomerService _customer;
        private readonly UserManager<IdentityUser> _userManager;
       


      

        public ProductController(IProductService productService, IReviewService reviewService, ApplicationDbContext context, IReviewRepository reviewRepository, IProductImageService imgService, ICustomerService customerService, UserManager<IdentityUser> userManager)
        {
            _productservice = productService;
            _reviewService = reviewService;
            _context = context;
            _reviewRepository = reviewRepository;
            _customer = customerService;
            _productImageService = imgService;
            _userManager = userManager;
    }
        public async Task<IActionResult> Details(int id)
        {
            ViewBag.ProductImages = await _productImageService.FindAll(id);
            var model = await _productservice.FindById(id);
            ViewData["Review"] = await _reviewService.FindReviewsById(id); 
            return View(model);

        }
        [HttpGet]
        public ActionResult CreateComment()
        {

            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateComment(string comment, int productId)
        {
            
            Review review = new Review();
            string id = _userManager.GetUserId(HttpContext.User);

           /* var claimsIdentity = this.User;
            var user = _context.Users.FirstOrDefault(x => x.Id == id);*/

            Product product = await _productservice.FindById(productId);
            Customer costumer = await _customer.FindByIdentityId(id);
            
            review.Comment = comment;
            review.Product = product;
            review.Customer = costumer;
            review.ProductId = product.Id;
            review.CustomerId= costumer.Id;
            review.DatePublished = DateTime.Now;

          
            Console.WriteLine(comment);
            var a = this._reviewService.Create(review);
            Console.WriteLine(a);
            /*            var productreviewed = _reviewRepository.FindById(productId);
            */


            return RedirectToAction("Details", new { id = productId });

        }


    }
}

Electon-Starlabs/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"]- SB Admin</title>
    <link href="~/AdminTheme/dist/css/styles.css" rel="stylesheet" />
    <link href="~/AdminTheme/ContactFrom_v2/css/main.css" rel="stylesheet" />
    <link href="~/AdminTheme/ContactFrom_v2/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css"/>
    <link href="~/AdminTheme/ContactFrom_v2/fonts/font-awesome-4.7.0/css/font-awesome.min.css"  rel="stylesheet" />
    <link href="~/AdminTheme/ContactFrom_v2/vendor/animate/animate.css"  rel="stylesheet" />
    <link href="~/AdminTheme/ContactFrom_v2/vendor/css-hamburgers/hamburgers.min.css"  rel="stylesheet" />
    <link href="~/AdminTheme/ContactFrom_v2/vendor/select2/select2.min.css"  rel="stylesheet" />
    <link href="~/AdminTheme/ContactFrom_v2/css/util.css"  rel="stylesheet" />
    <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="css/util.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.semanticui.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>

    <!-- Font Links-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@300&display=swap" rel="stylesheet">

    <style>
        .logout:hover {
            background-color: #D0312D;
            color: white;
            font-weight: 500;
        }
    </style>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" asp-controller="AdminHome" asp-action="Index">Admin Panel</a>
        <button class="btn btn-link btn-md order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <div class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0"></div>
        <!-- Navbar-->
        <a asp-area="" asp-controller="Home" asp-action="Index" style="color:white; font-weight:600;"><i class="fas fa-arrow-left mx-2"></i>Back to User</a>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" asp-controller="AdminHome" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" asp-action="Index" asp-controller="Customer" asp-area="Admin">
                            <div class="sb-nav-link-icon"><i class="fas fa-users-cog"></i></div>
                            Manage Customers
                        </a>
                        <a class="nav-link" asp-controller="Product" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Manage Products
                        </a>
                        <a class="nav-link" asp-area="Admin" asp-controller="Orders" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-shopping-bag"></i></div>
                            Manage Orders
                        </a>
                        <a class="nav-link" asp-controller="Category" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Manage Category
                        </a>
                        <a class="nav-link" asp-controller="ManageMessages" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-envelope"></i></div>
                            Contact
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div>
                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button type="submit" class=" btn btn-light logout">Log Out</button>
                        </form>
                    </div>

                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            @RenderBody()
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/AdminTheme/dist/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/AdminTheme/dist/assets/demo/chart-area-demo.js"></script>
    <script src="~/AdminTheme/dist/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="~/AdminTheme/dist/assets/demo/datatables-demo.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <!--===============================================================================================-->
    <script src="~/AdminTheme/ContactFrom_v2/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/AdminTheme/ContactFrom_v2/vendor/bootstrap/js/popper.js"></script>
    <script src="~/AdminTheme/ContactFrom_v2/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/AdminTheme/ContactFrom_v2/vendor/select2/select2.min.js"></script>
    <script src="//code.jquery.com/jquery-3.5.1.js"></script>
    <script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/1.11.3/js/dataTables.semanticui.min.js"></script>
    <script src="//cdn.datatables.net/1.11.3/js/dataTables.semanticui.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/AdminTheme/ContactFrom_v2/js/main.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-23581568-13');
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>